In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/tjoeun-jg-303/Downloads/hospital_addr_v4.0.csv') 
df

,level_0,index,name,addr
0,0,0,대한산업보건협회부설 서울의원,서울 금천구 디지털로9길 56
1,1,1,하늘마음한의원 금천점,서울 금천구 벚꽃로 286 리더스타워 2층
2,2,2,서울아산다온재활의학과의원,서울 금천구 디지털로 200 우리은행 가산IT타워 5층
3,3,3,가산안과의원,서울 금천구 가산디지털1로 168 우림 라이온스밸리 A동 106호
4,4,4,홀인원의원,서울 금천구 벚꽃로 298 대륭포스트타워6차 217호
...,...,...,...,...
19132,20068,20068,공중전화 위생병원행정관앞,서울 동대문구 휘경동 29-1
19133,20069,20069,공중전화 위생병원응급실,서울 동대문구 망우로 82
19134,20070,20070,하나은행365 경희의료원 치대병원,서울 동대문구 경희대로 26
19135,20071,20071,DV CAFE 경희대치과병원점,서울 동대문구 경희대로 26 1층
19136,20072,20072,공중전화 서울성심병원건너버스정류장,서울 동대문구 전농동 602-10

In [4]:
#열삭제
df = df.drop(['level_0','index'], axis=1)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19137 entries, 0 to 19136
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    19137 non-null  object
 1   addr    19137 non-null  object
dtypes: object(2)
memory usage: 299.1+ KB

In [6]:
#특정 문자가 포함된 행제거하기 

contain = df[~df['name'].str.contains('동물')]

In [7]:
contain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18968 entries, 0 to 19136
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18968 non-null  object
 1   addr    18968 non-null  object
dtypes: object(2)
memory usage: 444.6+ KB

In [9]:
contain.to_excel('C:/Users/tjoeun-jg-303/Downloads/hospital_addr_v4.1.xlsx', index=False)

In [10]:
df2= pd.read_excel('C:/Users/tjoeun-jg-303/Downloads/hospital_addr_v4.1.xlsx')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18968 entries, 0 to 18967
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        18968 non-null  object
 1   addr        18968 non-null  object
 2   Unnamed: 2  3275 non-null   object
 3   Unnamed: 3  3289 non-null   object
dtypes: object(4)
memory usage: 592.9+ KB

In [11]:
#의미있는 병원 데이터 추출을 위해 (성형외과 삭제)

contain2 = df2[~df2['name'].str.contains('성형')]

In [21]:
#파일 불러오기 
df3= pd.read_excel('C:/Users/tjoeun-jg-303/Downloads/hospital_addr_v4.1.xlsx')
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18968 entries, 0 to 18967
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18968 non-null  object
 1   addr    18968 non-null  object
 2   시군구명    18968 non-null  object
 3   동명      18968 non-null  object
dtypes: object(4)
memory usage: 592.9+ KB

In [22]:
contain3 = df3[~df3['name'].str.contains('성형')]

In [23]:
contain3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18343 entries, 0 to 18967
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18343 non-null  object
 1   addr    18343 non-null  object
 2   시군구명    18343 non-null  object
 3   동명      18343 non-null  object
dtypes: object(4)
memory usage: 716.5+ KB

In [24]:
import re
change_name = contain3['동명']
change_dong = []
for name in change_name:
    first = re.compile('[0-9,.$]+').sub("", name) #[0-9,·$]빼고 출력됨 
    # re.compile('[가-힣]+').findall(text)   #['신사', '동']

    change_dong.append(first)

In [25]:
contain3['동명']=change_dong
contain3.head()

<ipython-input-25-8761491e4686>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  contain3['동명']=change_dong

              name             addr 시군구명    동명
0  대한산업보건협회부설 서울의원    서울금천구디지털로9길56   금천구  가산동
1      하늘마음한의원 금천점      서울금천구벚꽃로286   금천구  가산동
2    서울아산다온재활의학과의원     서울금천구디지털로200   금천구  가산동
3           가산안과의원  서울금천구가산디지털1로168   금천구  가산동
4            홀인원의원      서울금천구벚꽃로298   금천구  가산동

In [26]:
#저장 
contain3.to_excel('C:/Users/tjoeun-jg-303/Downloads/hospitalv7.xlsx', index=False)

In [47]:
import pandas as pd
dup = pd.read_excel('G:/프로젝트/hospitalv8.xlsx')
dup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18262 entries, 0 to 18261
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18262 non-null  object
 1   addr    18262 non-null  object
 2   시군구명    18262 non-null  object
 3   동명      18262 non-null  object
dtypes: object(4)
memory usage: 570.8+ KB

In [7]:
#word가 포함된 행 삭제 
word = ('은행' , '동물', '주차장' , '성형','교회' ,'본죽')

In [80]:
contain =  dup[~dup.name.str.contains('본죽')]

In [81]:
contain1 =  contain[~contain.name.str.contains('주차장')]

In [82]:
contain2 =  contain1[~contain1.name.str.contains('CU')]
contain3 =  contain2[~contain2.name.str.contains('편의점')]
contain4 =  contain3[~contain3.name.str.contains('진료소')]
contain5 =  contain4[~contain4.name.str.contains('공차')]

In [83]:
not_unv = contain5[~contain5.name.str.contains('대학')]

In [84]:
unv = contain5[contain5.name.str.contains('대학')]

In [85]:
unv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 246 entries, 325 to 18250
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    246 non-null    object
 1   addr    246 non-null    object
 2   시군구명    246 non-null    object
 3   동명      246 non-null    object
dtypes: object(4)
memory usage: 9.6+ KB

In [86]:
#대학병원 중복된 주소 처리 
unv['addr'].duplicated().sum()

#중복된 주소 확인 
dup_unv = unv[unv['addr'].duplicated() ==True]

In [87]:
dup_unv

                       name          addr 시군구명    동명
511    가톨릭대학교여의도성모병원 응급의료센터   서울영등포구63로10  영등포구  여의동
531       가톨릭대학교 여의도성모병원 안과   서울영등포구63로10  영등포구  여의동
532      가톨릭대학교 여의도성모병원 신경과   서울영등포구63로10  영등포구  여의동
536       가톨릭 대학교여의도성모병원 외과   서울영등포구63로10  영등포구  여의동
541     가톨릭대학교 여의도성모병원 산부인과   서울영등포구63로10  영등포구  여의동
...                     ...           ...   ...  ...
18246      경희대학교한방병원 언어치료센터  서울동대문구경희대로23  동대문구  회기동
18247     경희대학교한방병원 신장내분비내과  서울동대문구경희대로23  동대문구  회기동
18248         경희대학교병원 내분비내과  서울동대문구경희대로23  동대문구  회기동
18249         경희대학교병원 집단급식소  서울동대문구경희대로23  동대문구  회기동
18250        경희대학교병원 의과학연구원  서울동대문구경희대로23  동대문구  회기동

[199 rows x 4 columns]

In [88]:
unv_drop = unv.drop_duplicates('addr')

In [89]:
unv_drop

                          name                addr 시군구명     동명
325                  고려대학교구로병원        서울구로구구로동로148   구로구   구로동
340               한림대학교 강남성심병원          서울영등포구신길로1  영등포구   대림동
359          한림대학교 강남성심병원 신관1동       서울영등포구시흥대로665  영등포구   대림동
464             가톨릭대학교 여의도성모병원         서울영등포구63로10  영등포구   여의동
706                    중앙대학교병원         서울동작구흑석로102   동작구   흑석동
1082         이화여자대학교의과대학부속서울병원        서울강서구공항대로260   강서구   발산동
1378              관악서울대학교 치과병원      서울관악구신림동150-18   관악구   대학동
2124            고려대학교구로병원 치과센터        서울구로구가마산로218   구로구   구로동
2416                   건국대학교병원       서울광진구능동로120-1   광진구   화양동
3790              한림대학교 한강성심병원     서울영등포구버드나루로7길12  영등포구  영등포동
3826   한림대학교 한강성심병원 화상전문응급의료센터       서울영등포구버드나루로55  영등포구  영등포동
3839               인제대학교 서울백병원           서울중구마른내로9    중구  을지로동
4178                 서울대학교치과병원         서울종로구대학로101   종로구   이화동
4734                 고려대학교안암병원         서울성북구고려대로73   성북구   안암동
4923             세브란스병원 치과대학병원      서울서대문구연세로18264  서대문구   신촌동
5050         연세대학교 세브란스체크업치과의원           서울중구통일로10    중구   회현동
5430                대학로힘정형외과의원       서울종로구율곡로219-1   종로구   이화동
6906             가톨릭대학교 은평성모병원        서울은평구통일로1021   은평구   진관동
6983                     대학한의원    서울은평구통일로83길44357   은평구   갈현동
7060          가톨릭대학교 은평성모병원 정문       서울은평구진관동107-5   은평구   진관동
7067                    구두대학병원       서울은평구불광동382-6   은평구   불광동
7440                 경희대학교치과병원        서울동대문구경희대로26  동대문구   회기동
7447                 경희대학교한방병원        서울동대문구경희대로23  동대문구   회기동
8146                   한양대학교병원      서울성동구왕십리로222-1   성동구   사근동
8814             차의과학대학교 강남차병원         서울강남구논현로566   강남구   역삼동
9053                 대학로서울안과의원         서울종로구대학로146   종로구   혜화동
9056              대학로 서울정형외과의원        서울종로구창경궁로264   종로구   혜화동
9074              대학로메리힐산부인과의원        서울종로구대학로12길4   종로구   이화동
10313             대전대학교 서울한방병원       서울송파구법원로11길32   송파구   문정동
11414            순천향대학교부속 서울병원         서울용산구대사관로59   용산구   한남동
11419             가톨릭대학교서울성모병원        서울서초구반포대로222   서초구   반포동
12603           연세대학교 강남세브란스병원         서울강남구언주로211   강남구   도곡동
13987      이화여자대학교 목동병원 협력의료센터       서울양천구안양천로1071   양천구    목동
14024              인제대학교 상계백병원        서울노원구동일로1342   노원구   상계동
14849            서울대학교직장부속치과의원           서울관악구관악로1   관악구   대학동
15009                노원을지대학교병원        서울노원구한글비석로68   노원구   하계동
16045              강동경희대학교의대병원         서울강동구동남로892   강동구   상일동
16339           고려대학교안암병원 장례식장        서울성북구개운사2길46   성북구   안암동
16351      고려대학교안암병원 응급의료센터 입구     서울성북구안암동5가126-1   성북구   안암동
16354         고려대학교안암병원 인공장기센터         서울성북구안암로145   성북구   안암동
17319               연세대학교 동문회관         서울서대문구연세로50  서대문구   신촌동
17872       순천향대학병원(한남오거리) 대여소      서울용산구한남동704-17   용산구   한남동
17892           순천향대학교서울병원어린이집  서울용산구대사관로34가길44245   용산구   한남동
17903             순천향대학교 무수혈센터      서울용산구한남동657-20   용산구   한남동
18007         강동경희대학교병원 입구 대여소         서울강동구상일동148   강동구   상일동
18014          강동 경희대학교병원 출입구2       서울강동구상일동148-1   강동구   상일동
18061           서울대학교병원 강남치과의원        서울강남구테헤란로152   강남구   역삼동

In [91]:
#대학병원과 아닌 데이터 합치기

result = pd.concat([not_unv, unv_drop])
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17975 entries, 0 to 18061
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    17975 non-null  object
 1   addr    17975 non-null  object
 2   시군구명    17975 non-null  object
 3   동명      17975 non-null  object
dtypes: object(4)
memory usage: 702.1+ KB

In [92]:
result = result.drop_duplicates()

In [93]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17973 entries, 0 to 18061
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    17973 non-null  object
 1   addr    17973 non-null  object
 2   시군구명    17973 non-null  object
 3   동명      17973 non-null  object
dtypes: object(4)
memory usage: 702.1+ KB

In [94]:
result.to_excel('G:/프로젝트/hospitalv9.xlsx',index= False)

In [49]:
#주소가 동일한 경우, 하나의 병원으로 통일한다. (대학 병원의 경우, 세분화된 시설들이 중복된 경우)
#중복된 주소 갯수
dup['addr'].duplicated().sum()

8519

In [51]:
#중복된 주소 확인 
dup_addr = dup[dup['addr'].duplicated() ==True]

In [54]:
dup_addr.to_excel('G:/프로젝트/중복된 주소목록.xlsx' , index = False)

In [45]:
contain3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18282 entries, 0 to 18342
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18282 non-null  object
 1   addr    18282 non-null  object
 2   시군구명    18282 non-null  object
 3   동명      18282 non-null  object
dtypes: object(4)
memory usage: 714.1+ KB

In [46]:
#파일 저장 
contain3.to_excel('G:/프로젝트/hospitalv8.xlsx', index=False)